apiVersion: v1
data:
  admin-password: fnBpZ3NmbHk=
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: monitoring-grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 6.6.1
    helm.sh/chart: grafana-5.0.0
  name: monitoring-grafana
  namespace: monitoring
type: Opaque
