#uses k3s built in lb that uses nodeports
apiVersion: v1
kind: Service
metadata:
  annotations:
    # which address pool to use form the metallb configmap 
    metallb.universe.tf/address-pool: network-services
    # key that tells metallb to share (must be same on both services UDP/TCP)
    metallb.universe.tf/allow-shared-ip: pihole-svc
  name: pihole-lb-udp
  namespace: pihole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  sessionAffinity: None
  loadBalancerIP: 192.168.10.220
  externalTrafficPolicy: Local
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
    - port: 67
      targetPort: client-udp
      protocol: UDP
      name: client-udp
  selector:
    app: pihole
