kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pihole
  namespace: pihole
  # can skip this annotation if storageClass is 'default'
  annotations:
    storageClassName: "managed-nfs-storage"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
